server:
  port: 8304
    
spring:
  application:
    name: client
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    # url: jdbc:mysql://localhost:3306/mstest
    # username: leon
    # password: leon
    url: jdbc:mysql://34.213.67.47/mstest
    username: mcb
    password: mcb
    #testWhileIdle: true
    #validationQuery: SELECT 1

auth-server: http://localhost:8080/api/kefelan-microservices-auth
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
#      user-info-uri: ${auth-server}/user
proxy:
  auth:
    load-balanced: true
logging:
  level:
    org.springframework.security: DEBUG
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost