server:
  port: 8301

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth
  data:
    mongodb:
      port: 27017
      database: auth_server

security:
  oauth2:
    resource:
      filter-order: 3