server:
  port: 8080

spring:
  application:
    name: zuul
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    # url: jdbc:mysql://localhost:3306/mstest
    # username: leon
    # password: leon
    url: jdbc:mysql://34.213.67.47/mstest
    username: mcb
    password: mcb
    #testWhileIdle: true
    #validationQuery: SELECT 1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
      
zuul:
  #Service will  be mapped under the /api URI
  #prefix: /api
  ignoredServices: '*'
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders: 
      url: http://localhost:8301
      serviceId: auth
    user:
      path: /user/**
      sensitiveHeaders: 
      url: http://localhost:8302
      serviceId: user
    note:
      path: /note/**
      sensitiveHeaders: 
      url: http://localhost:8303
      serviceId: note
  add-proxy-headers: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
        
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8080/auth/user
      prefer-token-info: false
         
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    