server:
  port: 8305
    
spring:
  application:
    name: resource
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    # url: jdbc:mysql://localhost:3306/mstest
    # username: leon
    # password: leon
    url: jdbc:mysql://34.213.67.47/mstest
    username: mcb
    password: mcb
    #testWhileIdle: true
    #validationQuery: SELECT 1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
      
security.oauth2.resource.token-info-uri: http://localhost:8080/api/kefelan-microservices-auth/oauth/check_token
security.oauth2.client.client-id: demo
security.oauth2.client.client-secret: demo

spring.jackson.date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat